const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教师管理",
                        "menuJump":"列表",
                        "tableName":"jiaoshi"
                    }
                ],
                "menu":"教师管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程信息管理",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                ],
                "menu":"课程信息管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"排课信息管理",
			            "menuJump":"列表",
			            "tableName":"paike"
			        }
			    ],
			    "menu":"排课信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"选课信息管理",
			            "menuJump":"列表",
			            "tableName":"xuanke"
			        }
			    ],
			    "menu":"选课信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"学生成绩管理",
			            "menuJump":"列表",
			            "tableName":"chengji"
			        }
			    ],
			    "menu":"学生成绩管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"班级管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryBanji"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"成绩类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryChengji"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"第几节管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJieke"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"课程类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKecheng"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"周次管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryXingqi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"学期管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryXueqi"
			        }
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "修改",
			            ],
			            "menu":"选课限制管理",
			            "menuJump":"列表",
			            "tableName":"xuankexianzhi"
			        }
			    ],
			    "menu":"选课限制管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"课程信息管理",
	                    "menuJump":"列表",
	                    "tableName":"kecheng"
	                }
	            ],
	            "menu":"课程信息管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			            ],
			            "menu":"排课信息管理",
			            "menuJump":"列表",
			            "tableName":"paike"
			        }
			    ],
			    "menu":"排课信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			            ],
			            "menu":"选课信息管理",
			            "menuJump":"列表",
			            "tableName":"xuanke"
			        }
			    ],
			    "menu":"选课信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生成绩管理",
			            "menuJump":"列表",
			            "tableName":"chengji"
			        }
			    ],
			    "menu":"学生成绩管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			            ],
			            "menu":"选课限制管理",
			            "menuJump":"列表",
			            "tableName":"xuankexianzhi"
			        }
			    ],
			    "menu":"选课限制管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	},
	 {
	        "backMenu":[
	            {
	                "child":[
	                    {
	                        "buttons":[
	                            "查看",
				                "选课",
	                        ],
	                        "menu":"课程信息管理",
	                        "menuJump":"列表",
	                        "tableName":"kecheng"
	                    }
	                ],
	                "menu":"课程信息管理"
	            }
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				            ],
				            "menu":"排课信息管理",
				            "menuJump":"列表",
				            "tableName":"paike"
				        }
				    ],
				    "menu":"排课信息管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "删除"
				            ],
				            "menu":"选课信息管理",
				            "menuJump":"列表",
				            "tableName":"xuanke"
				        }
				    ],
				    "menu":"选课信息管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看"
				            ],
				            "menu":"学生成绩管理",
				            "menuJump":"列表",
				            "tableName":"chengji"
				        }
				    ],
				    "menu":"学生成绩管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看"
				            ],
				            "menu":"选课限制管理",
				            "menuJump":"列表",
				            "tableName":"xuankexianzhi"
				        }
				    ],
				    "menu":"选课限制管理"
				}
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"公告信息管理",
	                        "menuJump":"列表",
	                        "tableName":"news"
	                    }
	                ],
	                "menu":"公告信息管理"
	            }
	        ],
	        "frontMenu":[],
	        "hasBackLogin":"是",
	        "hasBackRegister":"否",
	        "hasFrontLogin":"否",
	        "hasFrontRegister":"否",
	        "roleName":"学生",
	        "tableName":"yonghu"
	    }
]
    }
}
export default menu;
